package ui;

import entidad.Campo;
import entidad.EstadoCampo;
import entidad.Lote;
import entidad.TipoDeSuelo;
import gestor.GestorCampo;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariana Rodríguez
 */
public class PantallaRegistarCampo extends javax.swing.JFrame {
    private final GestorCampo gestor;
    private final List<TipoDeSuelo> tipos;
    private final EstadoCampo creado;
    private final TablaLotesModel tablaLotesModel;
    private Campo campo;
    private List<Lote> lotes;
    private PantallaCampoRegistrado pantalla;
    /**
     * Creates new form PantallaRegistarCampo
     */
    public PantallaRegistarCampo(List<TipoDeSuelo> tipos, EstadoCampo creado, GestorCampo gestor) {
        this.gestor = gestor;
        this.tipos = tipos;
        this.creado = creado;
        lotes = new ArrayList<Lote>();
        this.tablaLotesModel = new TablaLotesModel(lotes);
        this.campo = new Campo();
    
        initComponents();
        
        lbMensajeErrorCampo.setVisible(false);
        lbMensajeErrorLote.setVisible(false);
        tfNombreCampo.addMouseListener(new MouseAdapter(){
            public void mouseExited(MouseEvent e){
                lbMensajeErrorCampo.setVisible(
                        gestor.campoExistente(tfNombreCampo.getText())
                );
            }
        });

        tfNroLote.addMouseListener(new MouseAdapter(){
            public void mouseExited(MouseEvent e){
               lbMensajeErrorLote.setVisible(
                       loteExistente(Integer.parseInt(tfNroLote.getText()))
               );

            }
        });
    }
    private int sumaSuperficieLotes(List<Lote> lotes){
        int suma=0;
        for(Lote lote:lotes){
            suma+=lote.getSuperficie();
        }
        return suma;
    }
    private boolean loteExistente(int nro){
        boolean fueEncontrado=false;
        for(Lote lote:lotes){
            if(lote.getNro()==nro){
                fueEncontrado = true;
                break;
            }
        }
        return fueEncontrado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombre = new javax.swing.JLabel();
        lbSuperficie = new javax.swing.JLabel();
        lbHa = new javax.swing.JLabel();
        lbMensajeErrorCampo = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        tfSuperficieCampo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbAclaracion = new javax.swing.JLabel();
        lbSuperficie1 = new javax.swing.JLabel();
        tfSuperficieLote = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNroLote = new javax.swing.JTextField();
        lbHa1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTipoDeSuelo = new javax.swing.JComboBox<>();
        lbMensajeErrorLote = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btAgregarLote = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btCancelar = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        btQuitar = new javax.swing.JButton();
        btEditarLote = new javax.swing.JButton();
        tfNombreCampo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Campo");

        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNombre.setText("Nombre:");
        lbNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbSuperficie.setText("Superficie:");

        lbHa.setText("ha.");

        lbMensajeErrorCampo.setForeground(new java.awt.Color(255, 0, 0));
        lbMensajeErrorCampo.setText("Este campo ya está en uso.");

        lbUsuario.setText("Usuario: hmurakami");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lotes");

        lbAclaracion.setText("Tenga en cuenta que debe ingresar al menos 1 lote.");

        lbSuperficie1.setText("Superficie:");

        jLabel2.setText("Nro.:");

        lbHa1.setText("ha.");

        jLabel3.setText("Tipo de Suelo:");

        cbTipoDeSuelo.setModel(new javax.swing.DefaultComboBoxModel(tipos.toArray()));

        lbMensajeErrorLote.setForeground(new java.awt.Color(255, 0, 0));
        lbMensajeErrorLote.setText("Este nro. de Lote ya está en uso");

        btAgregarLote.setText("Agregar Lote");
        btAgregarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarLoteActionPerformed(evt);
            }
        });

        jTable1.setModel(tablaLotesModel);
        jScrollPane1.setViewportView(jTable1);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btRegistrar.setText("Registar Campo");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        btQuitar.setText("Quitar");
        btQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarActionPerformed(evt);
            }
        });

        btEditarLote.setText("Editar");
        btEditarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btAgregarLote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditarLote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btQuitar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbSuperficie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbHa)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbMensajeErrorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbAclaracion)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(lbSuperficie1))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfSuperficieLote)
                                                .addComponent(tfNroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbTipoDeSuelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbHa1))
                                .addComponent(lbMensajeErrorLote, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbMensajeErrorCampo)
                    .addComponent(lbUsuario)
                    .addComponent(tfNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSuperficie)
                    .addComponent(lbHa)
                    .addComponent(tfSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSuperficie1)
                            .addComponent(tfSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHa1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbTipoDeSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMensajeErrorLote))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarLote)
                    .addComponent(btQuitar)
                    .addComponent(btEditarLote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btRegistrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAgregarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarLoteActionPerformed
        Lote lote;
        int superficieCampo=Integer.parseInt(tfSuperficieCampo.getText());
        int superficieLote=Integer.parseInt(tfSuperficieLote.getText());
        int totalLotes = sumaSuperficieLotes(lotes);
        lbMensajeErrorLote.setVisible(loteExistente(Integer.parseInt(tfNroLote.getText())));
        lbMensajeErrorCampo.setVisible(gestor.campoExistente(tfNombreCampo.getText()));
        if(!lbMensajeErrorCampo.isVisible()&&!lbMensajeErrorLote.isVisible()){
            if(totalLotes+superficieLote <= superficieCampo){
                campo.setNombre(tfNombreCampo.getText());
                campo.setSuperficie(superficieCampo);
                campo.setEstadoCampo(creado);
                lote = new Lote(Integer.parseInt(tfNroLote.getText()),
                                superficieLote,
                                tipos.get(cbTipoDeSuelo.getSelectedIndex()),
                                campo
                );
                lotes.add(lote);
                tablaLotesModel.fireTableDataChanged();
            }else{
                JOptionPane.showMessageDialog(null, "Superficie de los lotes supera la del campo.", "Revisar superficie lotes", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            if(lbMensajeErrorCampo.isVisible())
                JOptionPane.showMessageDialog(null, "Este campo ya está en uso.", "Revise el nombre del campo", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "Este nro. de Lote ya está en uso.", "Revise el nro de lote", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btAgregarLoteActionPerformed

    private void btEditarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarLoteActionPerformed
        JOptionPane.showMessageDialog(null, "Fuera del alcance del caso de uso", "Alcance", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btEditarLoteActionPerformed

    private void btQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarActionPerformed
        JOptionPane.showMessageDialog(null, "Fuera del alcance del caso de uso", "Alcance", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btQuitarActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        int superficieCampo=Integer.parseInt(tfSuperficieCampo.getText());
        if(lotes.size()>=1){            
            int opcion = JOptionPane.showOptionDialog(null, 
                "Confirma el registro del campo?", 
                "Registrar Campo", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE, 
                null, null, null);
            if (opcion == JOptionPane.YES_OPTION)
            {
                campo.setNombre(tfNombreCampo.getText());
                campo.setSuperficie(superficieCampo);
                campo.setEstadoCampo(creado);
                int idCampo=gestor.agregarCampo(campo, lotes);
                pantalla = new PantallaCampoRegistrado(campo, lotes);
                pantalla.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos 1 lote.", "Revisar lotes ingresados", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarLote;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditarLote;
    private javax.swing.JButton btQuitar;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JComboBox<String> cbTipoDeSuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAclaracion;
    private javax.swing.JLabel lbHa;
    private javax.swing.JLabel lbHa1;
    private javax.swing.JLabel lbMensajeErrorCampo;
    private javax.swing.JLabel lbMensajeErrorLote;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbSuperficie;
    private javax.swing.JLabel lbSuperficie1;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField tfNombreCampo;
    private javax.swing.JTextField tfNroLote;
    private javax.swing.JTextField tfSuperficieCampo;
    private javax.swing.JTextField tfSuperficieLote;
    // End of variables declaration//GEN-END:variables
}
